How to import the Num py model 

import numpy as np

How arrray is created in num py

In [15]:
import numpy as np

x = np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


How list is created in num py

In [20]:
y = [1,2,3,4,5,6]
print(y)
print(type(y))


[1, 2, 3, 4, 5, 6]
<class 'list'>


exectutiuon time of hte list in python 

In [1]:
%timeit [i**4 for i in range(1,9)]

1.57 µs ± 29.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Exectuion of hte list in numpy 

In [9]:
%timeit np.arange(1,9)**4

1.18 µs ± 56.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


user input array in numpy

In [7]:
l =[]

for i in range(1,5):
    int_1 =int(input("enter: "))
    l.append(int(int_1))
print(np.array(l))

[1 2 3 1]


to print the dimension of array in numpy 

In [8]:
x = np.array([1,2,3,4,5])
print(x)
print(x.ndim)

[1 2 3 4 5]
1


two dimensional array in num py 

In [16]:
arr1 = np.array([[1,2,3,4,5],[2,3,4,5,3]])
print(arr1)
print(arr1.ndim)

[[1 2 3 4 5]
 [2 3 4 5 3]]
2


3 dim array in num py

In [19]:
arr2 =np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(arr2)
print(arr2.ndim)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]
3


To print n dimensions array

In [22]:
arn = np.array([1,2,3,4,5], ndmin =11)
print(arn)
print(arn.ndim)


[[[[[[[[[[[1 2 3 4 5]]]]]]]]]]]
11


Zeros Array in NUM py

In [24]:
arr_zero = np.zeros(4)
arr_zerod = np.zeros((4,4)) # zero array with dimesional of 4X4 
print(arr_zero)
print()
print(arr_zerod)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
